sudo: false
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - kalakris-cmake
    packages:
      - cmake
      - gcc-4.9
      - g++-4.9
      - clang-3.6
      - m4
      - valgrind
env:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

install:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

before_script:
  - mkdir build && cd $_
  - cmake -Dtest=ON ..
  - make

script:
  - valgrind --leak-check=yes --error-exitcode=1 ./tests/test-connection
  - valgrind --leak-check=yes --error-exitcode=1 ./tests/test-tls_connection

notifications:
  email: false

